---
# tasks file for openstack-cinder post install

- name: Ensure openstack-cinder services is started and enabled at boot.
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ cinder_system_service_name }}"
  notify: restart nova api


- name: Ensure openstack-cinder-volume services is started and enabled at boot.
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ cinder_volume_system_service_name }}"
