---
- name: Configure cinder nova.
  shell: |
    openstack-config --set "{{ cinder_nova_config_location }}" "{{ item.section }}" "{{ item.param }}" "{{ item.value }}"
  with_items:
    - "{{ cinder_nova_config }}"
