---
# tasks file for ansible-role-openstack-cinder

# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - always

- include: cinder_service_setup.yml
  run_once: True

# Setup/Install tasks.
- include: cinder_install_RedHat.yml
  when: ansible_os_family == 'RedHat'

# Configure tasks.
- include: cinder_configure.yml
  tags:
    - cinder-config

# DB tasks.
- include: cinder_db_setup.yml
  run_once: True
  tags:
    - cinder-db-setup

# Configure nova
- include: cinder_nova.yml

# Finalize installation tasks.
- include: cinder_post_install.yml
